# Generated by Django 4.2.5 on 2023-09-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="auteur",
        ),
    ]
